# Generated by Django 2.1.4 on 2018-12-28 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('user_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('user_pw', models.CharField(max_length=50)),
                ('user_name', models.CharField(max_length=50)),
                ('user_num1', models.CharField(blank=True, max_length=50)),
                ('user_num2', models.CharField(blank=True, max_length=50)),
                ('user_years', models.CharField(blank=True, max_length=50)),
                ('user_month', models.CharField(blank=True, max_length=50)),
                ('user_day', models.CharField(blank=True, max_length=50)),
                ('user_email', models.CharField(blank=True, max_length=50)),
                ('user_address', models.CharField(blank=True, max_length=50)),
                ('user_doctor_no', models.CharField(blank=True, max_length=50)),
                ('user_hospital_no', models.CharField(blank=True, max_length=50)),
                ('c_date', models.DateTimeField()),
            ],
        ),
    ]
