# Generated by Django 2.1.4 on 2018-12-29 09:20

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(blank=True, max_length=50)),
                ('user_name', models.CharField(max_length=50)),
                ('user_num1', models.CharField(blank=True, max_length=50)),
                ('user_num2', models.CharField(blank=True, max_length=50)),
                ('user_years', models.CharField(blank=True, max_length=50)),
                ('user_month', models.CharField(blank=True, max_length=50)),
                ('user_day', models.CharField(blank=True, max_length=50)),
                ('user_phone_1', models.CharField(blank=True, max_length=50)),
                ('user_phone_2', models.CharField(blank=True, max_length=50)),
                ('user_address', models.CharField(blank=True, max_length=50)),
                ('user_doctor_no', models.CharField(blank=True, max_length=50)),
                ('user_hospital_no1', models.CharField(blank=True, max_length=50)),
                ('user_hospital_no2', models.CharField(blank=True, max_length=50)),
                ('user_hospital_no3', models.CharField(blank=True, max_length=50)),
                ('c_date', models.DateTimeField(verbose_name=datetime.datetime(2018, 12, 29, 9, 20, 12, 601808))),
                ('user', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
