# Generated by Django 2.1.4 on 2018-12-28 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='user_hospital_no',
            new_name='user_hospital_no1',
        ),
        migrations.AddField(
            model_name='member',
            name='user_hospital_no2',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='member',
            name='user_hospital_no3',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='member',
            name='user_phone_1',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='member',
            name='user_phone_2',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
