# Generated by Django 2.1.4 on 2018-12-29 09:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20181229_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='c_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2018, 12, 29, 9, 48, 19, 600118)),
        ),
    ]
